name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment (dev or qa)'
        required: true
      deploy_aks:
        description: 'Deploy AKS in DEV environment? (true/false)'
        default: 'false'
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          if [ "${{ github.event.inputs.environment || 'dev' }}" == "dev" ]; then
            terraform -chdir=environments/dev init \
              -backend-config="storage_account_name=${{ secrets.DEV_TFSTATE_STORAGE_ACCOUNT_NAME }}" \
              -backend-config="access_key=${{ secrets.DEV_TFSTATE_STORAGE_KEY }}"
          else
            terraform -chdir=environments/qa init \
              -backend-config="storage_account_name=${{ secrets.QA_TFSTATE_STORAGE_ACCOUNT_NAME }}" \
              -backend-config="access_key=${{ secrets.QA_TFSTATE_STORAGE_KEY }}"
          fi

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.environment || 'dev' }}" == "dev" ]; then
            terraform -chdir=environments/dev plan \
              -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
              -var "deploy_aks=${{ github.event.inputs.deploy_aks || 'false' }}" \
              -var "admin_group_object_id=${{ secrets.AKS_ADMIN_GROUP_ID }}" \
              -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
              -out=tfplan
          else
            terraform -chdir=environments/qa plan \
              -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan
          fi

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: |
          terraform -chdir=environments/${{ github.event.inputs.environment || 'dev' }} apply tfplan # can be autoapprove but manually is safer
